---
events:
  reset:
    labels:
      - "Ne-am reîmprospătat forțele"
  fortune:
    labels:
      - "Am găsit oala cu aur a unui spiriduș"
  unfortune:
    labels:
      - "Am ratat autobuzul"
  neutral:
    labels: []
  course: []
  seminary: []
  laboratory: []
  quiz: []
  homework: []
  project: []
  exam: []
  good_food: []
  bad_food: []
  no_food: []
  hobby: []
  party: []
  study: []
  sleep: []
