---
game:
  player:
    name: "Levin"
  title:
    "Nu te supăra, Levin! (la AC)"
  timer:
    initial: 0
    unit: seconds
  credits:
    initial: 0
    maximum: 999
  dice:
    minimum: 1
    maximum: 6
  stats:
    intelligence:
      label: "Spor academic"
      initial: 50
      minimum: 1
      maximum: 100
    energy:
      label: "Energie"
      initial: 50
      minimum: 1
      maximum: 100
    luck:
      label: "Noroc"
      initial: 50
      minimum: 1
  levels:
    initial: 1
    maximum: 5
    1:
      credits_to_advance: 40
      label: "Anul I"
      board: >
        c<r<c<f<c<n<c<t
        v.............^
        t.............n
        v.............^
        c.............c
        v.............^
        f.............f
        v.............^
        c.............c
        v.............^
        n.............t
        v.............^
        s>c>c>n>c>c>r>c
    2:
      credits_to_advance: 100
      label: "Anul II"
      board: >
        c<r<c<f<c<n<c<t<c<n<c
        v...................^
        t...................n
        v...................^
        c...................c
        v...................^
        n...................r
        v...................^
        c...................c
        v...................^
        f...................f
        v...................^
        c...................c
        v...................^
        n...................t
        v...................^
        s>c>c>n>c>f>r>c>n>c>c
    3:
      credits_to_advance: 160
      label: "Anul III"
      board: >
        c<r<c<f<c<n<c<t<c<n<c<c<n<c<t
        v...........................^
        t...........................n
        v...........................^
        c...........................c
        v...........................^
        n...........................c
        v...........................^
        c...........................n
        v...........................^
        c...........................c
        v...........................^
        n...........................r
        v...........................^
        c...........................c
        v...........................^
        f...........................f
        v...........................^
        c...........................c
        v...........................^
        n...........................t
        v...........................^
        s>c>c>n>c>f>r>c>n>c>c>n>c>t>c
    4:
      credits_to_advance: 240
      label: "Anul IV"
      board: >
        c<r<c<f<c<n<c<t<c<n<c<c<n<c<t<c<r<n<c<n<c
        v.......................................^
        t.......................................n
        v.......................................^
        c.......................................c
        v.......................................^
        c.......................................c
        v.......................................^
        n.......................................n
        v.......................................^
        c.......................................f
        v.......................................^
        t.......................................c
        v.......................................^
        r.......................................t
        v.......................................^
        c.......................................c
        v.......................................^
        n.......................................r
        v.......................................^
        c.......................................c
        v.......................................^
        f.......................................f
        v.......................................^
        c.......................................c
        v.......................................^
        n.......................................t
        v.......................................^
        s>c>c>n>c>f>r>c>n>c>c>n>c>t>c>f>c>r>n>c>c
    5:
      credits_to_advance: 999
      label: "Ai absolvit!"
      board: >
        l<l<l<l
        v.....^
        l.....l
        v.....^
        s>l>l>l
  boxes:
    start:
      id: s
      label: "Start"
      events: [reset]
    random_event:
      id: r
      label: "Surprize, surprize!"
      events:
        - fortune: []
        - unfortune: []
        - neutral: []
    class:
      id: c
      label: "La facultă"
      events:
        - course: []
        - seminary: []
        - laboratory: []
        - quiz: []
        - homework: []
        - project: []
        - exam: []
    food:
      id: f
      label: "Ceva bun"
      events: 
        - good_food: []
        - bad_food: []
        - no_food: []
    spare_time:
      id: t
      label: "Timp liber"
      events:
        - hobby: []
        - party: []
        - study: []
        - sleep: []
    neutral:
      id: n
      label: "Nimic nou"
      events:
        - neutral: []
    levi9:
      id: l
      label: "Levi9"
      events:
        - levi9:
          - "Te așteptăm la Levi9 :)"
