---
game:
  player:
    name: "Levin"
  title:
    "Nu te supÄƒra, Levin! (la AC)"
  timer:
    initial: 0
    unit: seconds
  credits:
    initial: 0
    maximum: 999
  levels:
    initial: 1
    maximum: 5
  dice:
    minimum: 1
    maximum: 6
  