---
stats:
  intelligence:
    label: "Spor academic"
    initial: 50
    minimum: 1
    maximum: 100
  energy:
    label: "Energie"
    initial: 50
    minimum: 1
    maximum: 100
  luck:
    label: "Noroc"
    initial: 50
    minimum: 1
